database/dbproblem/데일리+실습_db_03_2_P/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

database/dbproblem/데일리+실습_db_03_2_P/practice1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('todos/', include('todos.urls')),
    path('admin/', admin.site.urls),
]

database/dbproblem/데일리+실습_db_03_2_P/todos/urls.py
from django.urls import path
from . import views

app_name="todos"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.toggle, name='toggle'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

database/dbproblem/데일리+실습_db_03_2_P/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

database/dbproblem/데일리+실습_db_03_2_P/todos/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Todo(models.Model):
    # db의 fk에는 user_id 라는 새 컬럼이 생김
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)
    

database/dbproblem/데일리+실습_db_03_2_P/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

database/dbproblem/데일리+실습_db_03_2_P/todos/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        # fields = '__all__'
        exclude = ('author', )

database/dbproblem/데일리+실습_db_03_2_P/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('todos:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)



def logout(request):
    auth_logout(request)
    return redirect('todos:index')

database/dbproblem/데일리+실습_db_03_2_P/todos/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_GET, require_safe
from django.contrib.auth.decorators import login_required
# from django.http import HttpResponse, HttpResponseForbidden
from .models import Todo
from .forms import TodoForm


# Create your views here.



@require_GET
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos,
    }
    return render(request, 'todos/index.html', context)



@require_http_methods(['GET', 'POST'])
def create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = TodoForm(request.POST)
            if form.is_valid():
                todo = form.save(commit=False)
                todo.author = request.user
                todo.save()
                return redirect('todos:index')
        else:
            form = TodoForm()
        context = {
            'form': form,
        }
        return render(request, 'todos/create.html', context)
    else:
        return redirect('accounts:login')

@require_POST
def toggle(request, pk):
    if request.user.is_authenticated:
        todo = Todo.objects.get(pk=pk)
        # todo 의 completed 값을 toggle
        if todo.completed is True:
            todo.completed = False 
        else:
            todo.completed = True
        todo.save()
        return redirect('todos:index')
    else:
        return redirect('accounts:login')

@require_POST
def delete(request, pk):
    todo = Todo.objects.get(pk=pk)
    # if request.user.is_authenticated:
    if request.user == todo.author:
        todo.delete()
        return redirect('todos:index')
    return redirect('todos:index')

database/dbproblem/데일리+실습_db_03_2_P/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todos</title>
</head>
<body>
  <div class="container">
   {% if request.user.is_authenticated %}
     <a href="#">NEW</a>
     <a href="{% url 'accounts:logout' %}">logout</a>
   {% else %}
     <a href="{% url 'accounts:login' %}">login</a>
     <a href="{% url 'accounts:signup' %}">signup</a>
   {% endif %}
  {% block content %}
  
  {% endblock content %}
  </div>
</body>
</html>

database/dbproblem/데일리+실습_db_03_2_P/todos/templates/todos/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'todos:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="작성">
  </form>
  <hr>
  <a href="{% url 'todos:index' %}">뒤로가기</a>
{% endblock content %}

database/dbproblem/데일리+실습_db_03_2_P/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>todos</h1>
  <a href="{% url 'todos:create' %}">CREATE</a>
  <hr>
  {% for todo in todos %}
    <p>글 번호 : {{ todo.pk }}</p>
    <p>제목 : {{ todo.title }}</p>
    <form action="{% url 'todos:toggle' todo.pk %}" method="POST">
      {% csrf_token %}
      {% if todo.completed == True %}
        <input type="submit" value="취소하기">
      {% else %}
        <input type="submit" value="완료하기">
      {% endif %}
    </form>
    {% if todo.author == user %}
      <form action="{% url 'todos:delete' todo.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제하기">
      </form>
    {% endif %}
    <hr>
  {% endfor %}
{% endblock content %}